
CREATE DATABASE QLTV
GO

USE QLTV
GO

CREATE TABLE DangNhap
(
	UserName NVARCHAR(100) PRIMARY KEY,
	PassWord NVARCHAR(100) NOT NULL,
	Type INT NOT NULL,
)
GO

CREATE TABLE NhanVien
(
	ID INT IDENTITY PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(1000) NOT NULL,
	SDT TEXT NOT NULL,
)
GO

CREATE TABLE DocGia
(
	ID INT IDENTITY PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(1000) NOT NULL,
	SDT TEXT NOT NULL,
)
GO

CREATE TABLE Sach
(
	ID INT IDENTITY PRIMARY KEY,
	TenSach NVARCHAR(100) NOT NULL,
	TenTacGia NVARCHAR(100) NOT NULL,
	NXB NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE ViTri
(
	ID INT IDENTITY PRIMARY KEY,
	IDSach INT NOT NULL,
	ViTri NVARCHAR(50) NOT NULL,
	SoLuong INT NOT NULL,
	FOREIGN KEY (IDSach) REFERENCES dbo.Sach(ID)
)
GO

CREATE TABLE Bill
(
	ID INT IDENTITY PRIMARY KEY,
	IDSach INT NOT NULL,
	FOREIGN KEY (IDSach) REFERENCES dbo.Sach(ID)
)
GO

CREATE TABLE BillInfo
(
	ID INT IDENTITY PRIMARY KEY,
	IDDG INT NOT NULL,
	IDBill INT NOT NULL,
	NgayMuon DATE NOT NULL,
	count INT NOT NULL,
	IDNhanVien INT NOT NULL,
	FOREIGN KEY (IDDG) REFERENCES dbo.DocGia(ID),
	FOREIGN KEY (IDBill) REFERENCES dbo.Bill(ID),
	FOREIGN KEY (IDNhanVien) REFERENCES dbo.NhanVien(ID)
)
GO


